### ISSUE TITLE
报这个错是什么原因

### ISSUE THREAD

**Issue by sky1001** [sjkummer/janus-gateway-js#142]
JanusError: Missing mandatory element (admin_key)
    at http://127.0.0.1:5500/dist/janus.js:9999:17
    at self._callback (http://127.0.0.1:5500/dist/janus.js:10479:27)
    at Transaction.execute (http://127.0.0.1:5500/dist/janus.js:10504:20)
    at Transactions.execute (http://127.0.0.1:5500/dist/janus.js:10572:24)
    at StreamingPlugin.executeTransaction (http://127.0.0.1:5500/dist/janus.js:10432:35)
    at StreamingPlugin.defaultProcessIncomeMessage (http://127.0.0.1:5500/dist/janus.js:10443:19)
    at http://127.0.0.1:5500/dist/janus.js:9949:19
From previous event:
    at Plugin.processIncomeMessage (http://127.0.0.1:5500/dist/janus.js:9944:9)
    at http://127.0.0.1:5500/dist/janus.js:11189:64
From previous event:
    at MediaPlugin.processIncomeMessage (http://127.0.0.1:5500/dist/janus.js:11188:21)
    at Session.processIncomeMessage (http://127.0.0.1:5500/dist/janus.js:10199:37)
    at Connection.processIncomeMessage (http://127.0.0.1:5500/dist/janus.js:9582:39)
    at Connection.<anonymous> (http://127.0.0.1:5500/dist/janus.js:9427:10)
    at EventEmitter.emit (http://127.0.0.1:5500/dist/janus.js:6066:22)
    at WebsocketConnection.onMessage (http://127.0.0.1:5500/dist/janus.js:12097:10)
    at WebsocketConnection.<anonymous> (http://127.0.0.1:5500/dist/janus.js:12008:10)

**Comment by sky1001** [comment]
I think there's a parameter wrong
![image](https://user-images.githubusercontent.com/49847551/180131126-88e85e11-14c7-4e08-9439-b0814ba7e098.png)
![image](https://user-images.githubusercontent.com/49847551/180131277-879914dc-e876-47eb-b8e9-d2b5ca4270b5.png)

**Comment by sjkummer** [comment]
Yes, this parameter from the integration tests is wrong/outdated. But I think the original reported error `JanusError: Missing mandatory element (admin_key)` is a Janus configuration isse.
